spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

fluent:
  api:
    key: ${fluent.api.key}
    username: ${fluent.api.username}
    password: ${fluent.api.password}

cloud:
  aws:
    s3:
      bucket: seoulmate7
    region:
      static: ap-southeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
